-- Procedimientos Almacenados para lote
-- Insertar lote
use fraccionamiento;
DELIMITER //
CREATE PROCEDURE InsertLote(IN _L_MANZANA char(3), IN _L_NUMERO char(6), IN _CA_CLAVE1 char(3), IN _CA_CLAVE2 char(3), IN _CA_CLAVE0 char(3), IN _L_TOTAL_M2 double, IN _L_IMPORTE double, IN _L_NUM_EXT char(6), IN _L_PAHT_MAP char(150), IN _L_FECHA_MANT datetime, IN _L_FECHA_POSIBLE datetime)
BEGIN
  INSERT INTO lote (L_MANZANA, L_NUMERO, CA_CLAVE1, CA_CLAVE2, CA_CLAVE0, L_TOTAL_M2, L_IMPORTE, L_NUM_EXT, L_PAHT_MAP, L_FECHA_MANT, L_FECHA_POSIBLE)
  VALUES (_L_MANZANA, _L_NUMERO, _CA_CLAVE1, _CA_CLAVE2, _CA_CLAVE0, _L_TOTAL_M2, _L_IMPORTE, _L_NUM_EXT, _L_PAHT_MAP, _L_FECHA_MANT, _L_FECHA_POSIBLE);
END //
DELIMITER ;
-- Modificar Lote
DELIMITER //
CREATE PROCEDURE UpdateLote(IN _L_MANZANA char(3), IN _L_NUMERO char(6), IN _CA_CLAVE1 char(3), IN _CA_CLAVE2 char(3), IN _CA_CLAVE0 char(3), IN _L_TOTAL_M2 double, IN _L_IMPORTE double, IN _L_NUM_EXT char(6), IN _L_PAHT_MAP char(150), IN _L_FECHA_MANT datetime, IN _L_FECHA_POSIBLE datetime)
BEGIN
  UPDATE lote
  SET CA_CLAVE1 = _CA_CLAVE1, CA_CLAVE2 = _CA_CLAVE2, CA_CLAVE0 = _CA_CLAVE0, L_TOTAL_M2 = _L_TOTAL_M2, L_IMPORTE = _L_IMPORTE, L_NUM_EXT = _L_NUM_EXT, L_PAHT_MAP = _L_PAHT_MAP, L_FECHA_MANT = _L_FECHA_MANT, L_FECHA_POSIBLE = _L_FECHA_POSIBLE
  WHERE L_MANZANA = _L_MANZANA AND L_NUMERO = _L_NUMERO;
END //
DELIMITER ;
-- Borrar lote
DELIMITER //
CREATE PROCEDURE DeleteLote(IN _L_MANZANA char(3), IN _L_NUMERO char(6))
BEGIN
  DELETE FROM lote
  WHERE L_MANZANA = _L_MANZANA AND L_NUMERO = _L_NUMERO;
END //
DELIMITER ;
